apiVersion: batch/v1
kind: Job
metadata:
  name: eck-cr
spec:
  template:
    spec:
      serviceAccountName: elastic
      initContainers:
      - name: wait-for-crd
        image: bitnami/kubectl
        - command:
        - "/bin/bash"
        - "-ec"
        - |
          timeout 120 bash -c '
          kubectl --for condition=established --timeout=120s crd/elasticsearch.k8s.elastic.co
          echo "Finished waiting for ECK CRDs to be created"'
      containers:
      - name: hooktainer
        image: bitnami/kubectl
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', '--']
        args:
        - |
            wait 10;
            cat <<EOF | kubectl apply -f -
            apiVersion: elasticsearch.k8s.elastic.co/v1
            kind: Elasticsearch
            metadata:
              name: elasticsearch
            spec:
              version: 7.5.2
              nodeSets:
                - name: default
                  count: 2
                  config:
                    node.master: true
                    node.data: true
                    node.ingest: true
                    node.store.allow_mmap: false
                  volumeClaimTemplates:
                  - metadata:
                      name: elasticsearch-data
                    spec:
                      accessModes:
                      - ReadWriteOnce
                      resources:
                        requests:
                          storage: 100Gi
            EOF
      restartPolicy: Never

